title: Daniel Rozek
description: "Special Olympics athlete with epilepsy."
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: neon
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  
navigation:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about/"
  - title: "Achievements"
    url: "/achievements/"
  - title: "Support Me"
    url: "/sponsors/"
    
head:
  custom: |
    <link rel="icon" href="/favicon_shoe.ico?v=1" type="image/x-icon">

author:
  name: "Daniel Rozek"
  avatar: "/assets/IMG_2025071106.jpg"
  bio: "Special Olympics athlete with epilepsy. 4x medalist at BC Summer Games 2025. Training for nationals and sharing my journey."
  links:
    - label: "Strava"
      icon: "fas fa-fw fa-running"
      url: "https://www.strava.com/athletes/danielrozek"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/crispruby"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielrozek/"
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://crispruby.github.io/"

footer:
  links:
    - label: "Strava"
      icon: "fas fa-fw fa-running"
      url: "https://www.strava.com/athletes/danielrozek"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/crispruby"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/danielrozek/"
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://crispruby.github.io/"
