title: Daniel Rozek Sports
description: "Special Olympics athlete with epilepsy — 4x medalist at BC Summer Games 2025"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: neon
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  
navigation:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about/"
  - title: "Achievements"
    url: "/achievements/"
  - title: "Support Me"
    url: "/sponsors/"
    
head:
  custom: |
    <link rel="icon" href="/favicon_shoe.ico?v=1" type="image/x-icon">
