remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  
navigation:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about/"
  - title: "Achievements"
    url: "/achievements/"
  - title: "Support Me"
    url: "/sponsors/"
    
head:
  custom: |
    <link rel="icon" href="/favicon_shoe.ico" type="image/x-icon">
